### ISSUE TITLE
A3.1: pulse panels state the actual period

### ISSUE THREAD

**Issue by jasonhnd** [jasonhnd/gitstarclub.com#371]
## Parent
#358 (A3).

## Current state
`PulsePageView` already computes `availablePeriodLabel` for week/month. Confirm every panel (week, month, year, all-time, on-this-day) shows the **actual** period and as-of, including fallback weeks.

## Work
- Audit `/` and `/pulse` (same view) for any panel that omits period / as-of or implies live GitHub.
- Fix copy and i18n.
- Add a snapshot or unit test on the label helper.

## Acceptance
- [ ] Each pulse list states its period
- [ ] Fallback week is labeled as such
- [ ] No “live from GitHub” wording

---

**Program:** #354 · **Map:** `docs/ROADMAP.md`  
**Promote:** `pre` → `main`. Do not weaken product-gates (#286).  
**Hard stops:** no request-path engine or database; no new content-body client JS; no request-time GitHub or LLM copy; no new per-request Blob existence probes; do not implement #362.

**Comment by jasonhnd** [comment]
Starting work on A3.1: audit PulsePageView period/as-of labels for week, month, year, all-time, and on-this-day panels (including fallback weeks), fix copy/i18n, and add a unit/snapshot test on the label helper. Branch: `feat/371-pulse-period-labels` from `pre`.

**Comment by jasonhnd** [comment]
PR open: https://github.com/jasonhnd/gitstarclub.com/pull/393

**What changed**
- Extracted `availablePeriodLabel` / `formatPulseListMeta` / fallback detectors to `web/lib/rank-period-labels.ts` with unit tests.
- Pulse week, month, year, all-time, and on-this-day panels now show concrete period + as-of.
- Fallback weeks/months are labeled **Latest available: {period}**.
- Softened Pulse subtitle/meta/titles so they do not imply live calendar or live GitHub.
- Shared helpers with rankings period switchers; dictionary keys updated for all 7 locales (`common.periodAsOf` + copy).

**Validation**
- `bun test` on `rank-period-labels` + dictionary-parity
- lint on touched files
- `typecheck:tests`

Does not implement #372.

**Comment by jasonhnd** [comment]
Closed by merge of #393 into pre. Default branch is main so auto-close did not fire.
